edgexfoundry/edgex-global-pipelines

.gitmodules
README.md
vars/edgeXScmCheckout.groovy
vars/edgeXSemver.groovy
vars/edgeXSetupEnvironment.groovy

First commit. Moving code from https://github.com/ernestojeda/edgex-global-pipelines.
Added global-jjb submodule

Initialize repository

---

vars/edgeXPRStage.groovy
vars/edgeXReleaseStage.groovy

Add two new global vars for release and PR stages

---

vars/edgeXMergeStage.groovy
vars/edgeXPRStage.groovy

Testing updated log message to include branchName

---

vars/edgeXMergeStage.groovy
vars/edgeXPRStage.groovy

allow git-semver for testing

---

vars/edgeXDockerLogin.groovy

Add edgeXDockerLogin function

---

LICENSE
vars/edgeXDockerLogin.groovy
vars/edgeXMergeStage.groovy
vars/edgeXPRStage.groovy
vars/edgeXScmCheckout.groovy
vars/edgeXSemver.groovy
vars/edgeXSetupEnvironment.groovy

Add license and copyright notices

---

vars/edgeXInfraPublish.groovy
vars/edgeXInfraShipLogs.groovy

Add LF post build scripts

---

vars/edgex.groovy

[WIP] add new edgex utility library

---

vars/edgeXSetupEnvironment.groovy

add ability to call with null git vars

---

vars/edgeXInfraShipLogs.groovy

Remove duplicate PR link in description

---

vars/edgex.groovy

add new method to detect changes in a git commit

---

vars/edgex.groovy

added debug statements

---

vars/edgex.groovy

update default previous branch to be master

---

vars/edgex.groovy

do not error on debug statement

---

vars/edgex.groovy

calculate the previous commit hash on master

---

vars/edgeXInfraLFToolsSign.groovy

Tested signing tags and directory on sandbox using sample service. Signed images/containers still remains untested.

Add lftools sign function

---

vars/edgeXInfraLFToolsSign.groovy

Update LFToolsSign to use edgex-lftools image

---

vars/edgeXCodecov.groovy

Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>

Add function for codecov

---

vars/edgeXClair.groovy

add edgeXClair library to enable docker vulnerability scans

---

vars/edgeXClair.groovy

update klar image to use

---

vars/edgeXInfraShipLogs.groovy

use lftools base image to publish logs

---

vars/edgeXInfraShipLogs.groovy

switch to alpine based lftools publish

---

vars/edgeXNexusPublish.groovy

add new library var to publish zip files to nexus

---

vars/edgeXNexusPublish.groovy

add support for different vm architectures

---

vars/edgeXClair.groovy

Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>

update default server to LF hosted server

---

vars/edgeXSnyk.groovy

Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>

Add global function to run snyk scans

---

vars/edgeXSnyk.groovy

use monitor command instead of test

---

vars/edgeXSnyk.groovy

refactor to fix issues related to the Groovy script sandbox
add null values to make arguments optional

refactor to fix issues related to the Groovy script sandbox

---

vars/edgeXSemver.groovy

**Summary of Changes**
Updated edgeXSemver global function to be idempotent.
Call to edgeXSemver Init checks HEAD to see if it is tagged, if it is then it will set an environment variable called GITSEMVER_HEAD_TAG. All subsequent calls to edgeXSemver tag, bump, or push will be ignored if the GITSEMVER_HEAD_TAG environment variable is set.
**What was Tested**
Testing was done using the [sample-service](https://github.com/edgexfoundry/sample-service) repository.  Two following jobs were setup on the Sandbox server to facilitate testing:
sample-service-verify-pipeline
sample-service-merge-pipeline
**Test 1**:  Merge PR into sample-service with no previous version
Result: Job succeeds and git semver executes tag, bump and push tag to v0.0.0
[Build …

Update edgeXSemver commands to be idempotent

---

vars/edgex.groovy

Add fuji to release streams

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXDocker.groovy
vars/edgeXDockerLogin.groovy
vars/edgeXGeneric.groovy
vars/edgeXSemver.groovy
vars/edgeXSetupEnvironment.groovy
vars/edgex.groovy

This PR introduces two fully implemented Jenkins Declarative Pipeline to easily build docker images as well as build Golang based code.
The new pipelines are (_names are TBD_):
I have created a few jobs on the Jenkins sandbox to demonstrate the new Jenkinsfile syntax.
https://jenkins.edgexfoundry.org/sandbox/view/All/job/geneva-app-functions-sdk-go-verify-pipeline/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/geneva-app-service-configurable-verify-pipeline/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/geneva-device-bacnet-c-verify-pipeline/
https://jenkins.edgexfoundry.org/sandbox/view/All/job/geneva-device-sdk-c-verify-pipeline/
More of the exact syntax will be written up in a future document.

New global pipelines for GoLang and Docker builds

---

vars/edgeXDocker.groovy

Add semver branch to pushed docker tags

---

Jenkinsfile

add git-semver support

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXDocker.groovy

Implement the ability to push to different nexus repositories

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy

add push condition for edgeXBuildGoApp, and misc fixes

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoMod.groovy

add new global pipeline library to handle Go module defaults

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoMod.groovy

add ability to control semver bump level (default pre)

---

vars/edgeXBuildGoApp.groovy

add missing underscore

---

vars/edgeXBuildGoApp.groovy

codecov does not require isReleaseStream as per the current builds

---

vars/edgeXBuildGoApp.groovy

stash coverage report for later CodeCov stage

---

vars/edgeXBuildDocker.groovy

add new option to allow custom release branch override

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy

move Clair stage back to the main x86_64(amd64) based agent

---

vars/edgeXBuildGoApp.groovy

add customWorkspace path to fix go mod tidy issues

---

test/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildGoApp.groovy

Update golang 1.12 version in edgeXBuildGoApp

---

vars/edgeXSnyk.groovy

Add org= according to: https://support.snyk.io/hc/en-us/articles/360000920738-Choosing-the-organisation-to-use-in-the-CLI

add org name

---

vars/edgeXInfraShipLogs.groovy

remove reference to env.ghprbPullId

---

vars/edgeXBuildGoApp.groovy

use project from config rather than environment

---

scripts/update-named-tag.sh

The script used internally to update named tags e.g. stable, experimental to a specific versioned tag.

new script to update a named tag

---

test/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildGoApp.groovy

add GOPROXY support

---

vars/edgeXGeneric.groovy

unstash not needed when sharing mainNode

---

test/edgeXBuildCAppSpec.groovy
vars/edgeXBuildCApp.groovy

Add edgeXBuildCApp function

---

vars/edgeXBuildCApp.groovy

Turn off CodeCov block in edgeXBuildCApp since we don't have a coverage report

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy

Fix bug with Synk and Clair image scanning

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy

Disable snyk scans for non-Go pipelines

---

vars/edgeXBuildGoApp.groovy

fix clair scan for Go App based images

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXGeneric.groovy

Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
Test Links :

[WIP] Update the global library to include the regex that EdgeX uses

---

Jenkinsfile

Add new stage to automatically move experimental tag on release stream (master)
Test Links :
N/A - Cannot be tested on the sandbox

add auto bump of experimental tag

---

Jenkinsfile

Add ssh-agent to allow authentication of git commands

---

Jenkinsfile

re-organize stages

---

Jenkinsfile

remove lf functions

---

Jenkinsfile

revert experimental tagging

---

Jenkinsfile

add script to auto bump experimental tag

---

scripts/update-named-tag.sh

remove -s argument

---

test/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildGoApp.groovy

New feature to support non-alpine based builds
N/A
N/A

add new option for alpine based builds

---

test/edgeXDockerSpec.groovy
vars/edgeXDocker.groovy

pass in ARCH as a build-arg in edgeXDocker.build

---

vars/edgeXSnap.groovy

Initial commit of the snap global function to test functionality of the pipeline on the Jenkins sandbox.
Test Links :

Initial commit of the snap global function

---

vars/edgeXSnap.groovy

add check for copy command if production Jenkins

---

test/edgeXReleaseDockerHubSpec.groovy
test/edgeXReleaseDockerNexusSpec.groovy
test/edgeXReleaseGitTagSpec.groovy
test/edgeXReleaseSnapSpec.groovy
test/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy
vars/edgeXReleaseDockerHub.groovy
vars/edgeXReleaseDockerNexus.groovy
vars/edgeXReleaseGitTag.groovy
vars/edgeXReleaseSnap.groovy

Test Links : TBD
Will be testing these functions in edgexfoundry-holding/cd-management. Also demo in the next DevOps WG.

Add edgeXRelease skeleton functions and first round of unit tests

---

test/edgeXInfraLFToolsSignSpec.groovy
vars/edgeXInfraLFToolsSign.groovy

Signed-off-by: James Gregg <james.r.gregg@intel.com>
https://github.com/edgexfoundry/ci-build-images/issues/116
Test Links :

update lftools v0.31.0

---

test/edgeXInfraLFToolsSignSpec.groovy
vars/edgeXInfraLFToolsSign.groovy

revert to working version of lftools

---

Jenkinsfile
scripts/linter.sh

Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
Test Links :

US5858: EdgeX DevOps: figure out how to lint groovy code

---

Jenkinsfile

update to use new gradle based cache image

---

src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

refactor edgeXRelease to use regular for loops

---

vars/edgeXRelease.groovy
vars/edgeXReleaseDockerImage.groovy

Signed-off-by: Venkata Lakshmi Dhatri Penna <venkata.lakshmi.dhatrix.penna@intel.com>
Test Links :

Updated ReleaseDockerImages to include method to publishDockerimages

---

build.gradle
src/test/groovy/edgeXDockerSpec.groovy
src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXDocker.groovy
vars/edgeXRelease.groovy
vars/edgeXReleaseDockerImage.groovy

refactor to use docker image parser

---

vars/edgeXReleaseDockerImage.groovy

remove NonCPS and update inline documentation

---

src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXReleaseDockerImage.groovy

Add missing docker pull command and updated unit tests.
Test Links :

add docker pull command

---

src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXReleaseDockerImage.groovy

add edgeXDockerLogin

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

Fixed bug with sigul signing execution and implemented ability to respect **DRY_RUN**
Sandbox Testing cannot be accomplished.
I attempted to implement DRY practices by implementing the `executeCommands` function but was unable to get it to work on our internal Jenkins servers thus not going to attempt it for EdgeX, leaving it for a future  attempt
All source code has accompanying unit tests:
```
> Task :test
Results: SUCCESS (17 tests, 17 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 21s
```

Update edgeXReleaseGitTag fix sign bug and implement DRY_RUN

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

add bannerMessage before shell script

---

vars/edgeXSnap.groovy

remove newlines and spaces from snapName

---

scripts/linter.sh

Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Currently the `Linter script` reports an error only for the first file it lints, it wont proceed further for linting other such files or for files without errors. This can mislead the user on possible linting issues for the groovy pipeline files.
This PR which includes `scripts/linter.sh`, changes the functionality on how we are currently handling erroneous groovy pipeline it hits and move on beyond that to lint other required files.
```
[Pipeline] { (Lint Pipelines)
[Pipeline] sh
./scripts/linter.sh
vars/edgeXBuildCApp.groovy successfully validated
vars/edgeXBuildDocker.groovy successfully validated
Errors encountered validating Jenkinsfile: WorkflowScript: 213: Unknown stage section "allOf". Starting with version 0.5, steps …
```

change the method flow how linting happens

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

The following PR addresses the following items:
- Update exception handling for `releaseGitTag` function to properly handle errors 
- Leverage `isDryRun` method from edgeX global library
Issue was encountered during functional testing - no issue was created
NA

Update releaseGitTag exception handling add isDryRun reuse

---

src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXReleaseDockerImage.groovy

View test results here: https://asciinema.org/a/mlOQPzmRAgT7dTedOBGgS799t
The docker image list will eventually become hard to manage for certain repos so I refactored the yaml to group the source/destination docker images together in an object, rather than having to search through two separate lists.
```Bash
./gradlew cleanTest test --tests "EdgeXReleaseDockerImageSpec"
> Task :test
Results: SUCCESS (5 tests, 4 successes, 0 failures, 1 skipped)
BUILD SUCCESSFUL in 12s
5 actionable tasks: 2 executed, 3 up-to-date
```
View test results here: https://asciinema.org/a/mlOQPzmRAgT7dTedOBGgS799t

refactor yaml to reduce code complexity

---

vars/edgeXRelease.groovy

remove dockerSource reference after refactor

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

This PR addresses a bug discovered during integration testing of EdgeXReleaseGitTag within cd-management, specifically when executing parallel steps. This update will ensure that all relevant commands are executed within the desired directory (i.e. the target repo cloned directory).
NA
All unit tests passed:
```
> Task :test
Results: SUCCESS (15 tests, 15 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 21s
> Task :test
Results: SUCCESS (142 tests, 139 successes, 0 failures, 3 skipped)
BUILD SUCCESSFUL in 2m 40s
```

Fix bug with EdgeXReleaseGitTag working dir within parallel steps

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

Attempt to simplify previous commit lookup logic.
Test Links :

ci(groovy): update previous to origin/HEAD

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

revert prev logic and add release check

---

Jenkinsfile

use setProperty when setting environment vars

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: James Gregg <james.r.gregg@intel.com>
Update PR template to add new question regarding added dependencies (e.g. new imports / modules) as per decision in Architect's meeting 06/15/2020
Test Links :

docs: update pr template to add new dependencies question

---

Jenkinsfile

Fix issue with branch name for when conditional

---

Jenkinsfile

remove edgeXSetupEnvironment due to issues with GIT_BRANCH

---

src/test/groovy/edgeXDockerSpec.groovy
vars/edgeXDocker.groovy

This PR adds a new function in `edgeXDocker.groovy` that allows the user to build `n` number of docker images in parallel levering a feature in docker-compose. An ephemeral docker-compose yaml file is written to the Jenkins workspace to accomplish this task.  See below for input data format and usage.
```
Transform input data and write ephemeral docker-compose.yaml
execute docker-compose build -f <ephemeral-compose> --parallel
```
```Groovy
Array<Map>
[image: '<final-image-name>', dockerfile: '<path/to/Dockerfile>']
```
```Groovy
// dockers can be generated in whatever fashion required
def dockers = [
[image: 'image-1-go', dockerfile: 'cmd/image-1/Dockerfile'],
[image: 'image-2-go', dockerfile: 'cmd/image-2/Dockerfile']
]
edgeXDocker.buildInParallel(dockers)
...
$ docker images
REPOSITORY …
```

add new function to build docker images in parallel with docker-compose

---

resources/edgex-publish-swagger.sh

fix non-standard ascii char

---

src/test/groovy/edgeXBuildDockerSpec.groovy
vars/edgeXBuildDocker.groovy

add new config param to control whether to push latest tag

---

src/test/groovy/edgeXDockerSpec.groovy
vars/edgeXDocker.groovy

fix issue with docker.image not grabbing the correct image

---

src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXClairSpec.groovy
src/test/groovy/edgeXDockerSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXClair.groovy
vars/edgeXDocker.groovy
vars/edgex.groovy

Test Links :
edgex-go using this new pipeline:
https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/edgexfoundry%2Fedgex-go/activity

feat: initial commit of edgeXBuildGoParallel for edgex-go replacement

---

src/test/groovy/edgeXDockerSpec.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXDocker.groovy

fix: pushAll ignores arm64 image name suffix

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Just a simple PR to disable the `Test` stage when code is being merged to master.
Test Links :

disable Test stage when merging to master

---

vars/edgeXBuildGoApp.groovy

fix: codecov stage should not run on master

---

vars/edgeXSemver.groovy

fix: add option for git-semver arm64 docker image

---

Jenkinsfile
build.gradle
gradle/wrapper/gradle-wrapper.properties

You can see Gradle similar `--scan` results here: https://scans.gradle.com/s/x5wtqliyzlwxa.
Test Links :

feat: Add support for parallel test execution

---

src/test/groovy/edgeXBuildCAppSpec.groovy
vars/edgeXBuildCApp.groovy

Update `edgeXBuildCApp` with the the same Snap modifications as `edgeXBuildGoApp`
Test Links :

ci: update snap stage for C apps

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

bug: fix customWorkspace issue

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

Implement missing feature from [edgeXBuildDocker](https://github.com/edgexfoundry/edgex-global-pipelines/blob/master/vars/edgeXBuildDocker.groovy#L290)
Test Links :

feat: add dockerBuildArgs config parameter

---

src/test/groovy/edgeXInfraShipLogsSpec.groovy
vars/edgeXInfraShipLogs.groovy

Add sar file conversion technique. This PR will need to be merged after this PR: https://github.com/edgexfoundry/ci-build-images/pull/146
Test Links :
TBD

feat: update sysstat steps after upstream image change

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

fix: go version needs to be wrapped within base image

---

README.md

feat: add build icon on README

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildGoApp.groovy

This is a modification to `edgeXBuildGoApp` to account for different types of build artifacts. The initial version of `edgeXBuildGoApp` only allowed for `docker` type artifacts. This change introduces a new type of artifact named `archive` (tar, zip, etc). When building archive artifacts we rely on the user providing a script or make target that will generate said artifacts. Two new pipeline config parameters are introduced to control trigger this new behavior.
- `artifactTypes`, Array, default: ['docker']. This default will let the existing pipelines function as is. Options include docker, archive. Any unknown type will not trigger the build stage. This is exported to the environment as the `ARTIFACT_TYPES` environment variable each type separated by space.
- `artifactRoot `, String, …

feat: modify edgeXBuildGoApp to include different artifact types

---

src/test/groovy/edgeXSwaggerPublishSpec.groovy
vars/edgeXSwaggerPublish.groovy

https://github.com/edgexfoundry/edgex-go/issues/2698
Test Links :
No

fix: edgeXSwaggerPublish - make DRY_RUN default to false unless explicitly defined as 'true'

---

vars/edgeXBuildGoApp.groovy

fix: issue with env.ARCH in buildArtifact

---

docs/manual-bump.md

docs: update named branch documentation

---

src/test/groovy/edgeXInfraPublishSpec.groovy
vars/edgeXInfraPublish.groovy
vars/edgeXInfraShipLogs.groovy

feat: add docker support for lfInfraShipLogs

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

Add main as valid releaseStream

---

Jenkinsfile

fix: publish on isolated node

---

Jenkinsfile
docs/index.html

fix: update script for html directory

---

Jenkinsfile

fix: To speed up publish github pages stage
Test Links :

fix: To speed up publish github pages stage

---

docs_src/md_files/header.md

docs: update header with WIP

---

src/test/groovy/edgeXSemverSpec.groovy
vars/edgeXSemver.groovy

fix: permission change for .semver directory

---

Jenkinsfile

feat: use dockerfile as agent for mkdocs stage

---

src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

feat(jenkins)remove logic to publish snaps from release execution

---

vars/edgeXInfraPublish.groovy

fix: log publishing errors should not fail the builds

---

src/test/groovy/edgexSpec.groovy

fix: Unit tests method signatures renamed to be unique
Test Links :

fix: Unit tests method signatures renamed to be unique

---

src/test/groovy/edgeXDocGeneratorSpec.groovy

fix: Mocking file object for fetchIndexHeader unit test
Test Links :

Mocking file object for fetchIndexHeader unit test

---

.gitignore
Jenkinsfile
resources/github-pages-publish.sh
src/test/groovy/edgeXGHPagesPublishSpec.groovy
vars/edgeXGHPagesPublish.groovy

feat(jenkins): Shared library for github-pages publish
Test Links :

feat(jenkins): Shared library for github-pages publish

---

mkdocs.yml

add link to pr-commit tutorial

---

Jenkinsfile
vars/edgeXGHPagesPublish.groovy

refactor: Additional fixes for publishing GitHub pages
Test Links :

refactor: Additional fixes for publishing GitHub pages

---

docs_src/tutorials/unit-testing-guidance.md
mkdocs.yml

Add documentation describing prescriptive guidance for facilitating unit testing of Jenkins declarative pipeline logic.
Fixes https://github.com/edgexfoundry/edgex-global-pipelines/issues/194
NA

docs(jenkins): Add documentation for unit testing prescriptive guidance

---

resources/github-pages-publish.sh
src/test/groovy/edgeXGHPagesPublishSpec.groovy
vars/edgeXGHPagesPublish.groovy

fix: Commit message in gh-pages branch
Test Links :

fix: Commit message in gh-pages branch

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

Revert back to launching isolated node for amd64 builds to fix permissions issues.
Test Links :

fix: launch isolated node for amd64 builds

---

vars/edgeXBuildGoParallel.groovy

This is not needed anymore after Go 1.15.
Test Links :

ci: remove GOTESTFLAGS

---

docs_src/tutorials/unit-testing-best-practices.md
docs_src/tutorials/unit-testing-guidance.md
mkdocs.yml

- renamed doc to 'unit testing best practices'
- consolidated unit testing BKM document from wiki; will remove wiki once this PR is merged
Test Links :

docs(jenkins): Rename and consolidate unit testing best practices

---

Jenkinsfile
vars/edgeXGHPagesPublish.groovy

Just some code styling changes. Also I updated the Jenkinsfile to be explicit about what stash is being published to make it hopefully more clear.
Test Links :

style: update code style and include stashName

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

feat: add hanoi to valid release stream

---

vars/edgeXBuildCApp.groovy

bug: fix Snyk C scan image name

---

src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
vars/edgeXReleaseDockerImage.groovy

feat(ci): add verification and force feature of docker images in release flow.
**Would prefer to wait until after Hanoi releases to merge this.**
https://github.com/edgexfoundry/cd-management/issues/40
Test Links :
[Docker Hub Link](https://hub.docker.com/r/edgexfoundry/docker-sample-service/tags)
Initial State: 
`sample-service 4.1.25 exists on dockerhub.`
First Build:
Push 4.1.26, no force flag -- Success
[Build Job](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/PR-88/12/console)
Output
`15:45:29  [edgeXReleaseDockerImage] Successfully published [2] images`
Second Build:
Push 4.1.26 again, no force flag -- …

feat(ci): add verification and force feature of docker images in release flow

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

fix: require check before running edgeXDockerLogin

---

src/test/groovy/edgeXBuildGoModSpec.groovy
vars/edgeXBuildGoMod.groovy

fix: revert go module semver bump change

---

resources/edgex-publish-swagger.sh

bug: publish via curl @file rather than raw cat

---

resources/edgex-publish-swagger.sh

fix: use --data-binary instead of -d

---

src/test/groovy/edgeXBuildGoModSpec.groovy
vars/edgeXBuildGoMod.groovy

feat: Go modules bump pre-release version now

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildDockerSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

refactor: Cleaning up edgeXSnyk docker image scan stages from global pipelines
Test Links :

refactor: Cleaning up edgeXSnyk docker image scan stages from global pipelines

---

resources/snap-build.sh

Replace the optimization patch used to reduce the snap build time in the CI pipeline
with a new script that removes the parts of snapcraft.yaml that are not required.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
Test Links :
With this change, the optimization patch is no longer required for the CI pipeline build process.

feat(snap): replace optimization patch with new script

---

src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

#326 
Test Links :
Functional Testing Results:
Releasing repository with no Jenkinsfile i.e. 'tag-only' release: [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/9/pipeline/183)
Releasing repository with Jenkinsfile (Success): [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/12/pipeline)
Releasing repository with Jenkinsfile (Normal Failure): [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/11/pipeline)
Prior behavior of a 'tag-only' release was a build …

feat: only fail stage artifact stage if possible to build artifact

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoMod.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

feat: make Go 1.16 the default Go version

---

vars/edgeXBuildGoParallel.groovy

Needed to support switch to latest tag by core
Test Links :

feat: use latest tag when pushing images

---

mkdocs.yml
vars/edgeXBuildGoParallel.groovy

ci: disable snap builds temporary due to upstream Go issue

---

mkdocs.yml
vars/edgeXBuildGoParallel.groovy

- [x ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
Test Links :

ci: enable snap builds again and fix google analytics tag

---

.github/PULL_REQUEST_TEMPLATE.md
Jenkinsfile
README.md
docs_src/tutorials/docker-build-strategy.md
docs_src/tutorials/pr-commit-for-testing.md
docs_src/tutorials/unit-testing-best-practices.md
src/test/groovy/edgeXDockerSpec.groovy
src/test/groovy/edgeXEmailUtilSpec.groovy
src/test/groovy/edgeXGenericSpec.groovy
src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
src/test/groovy/edgeXReleaseDockerImageSpec.groovy
src/test/groovy/edgeXReleaseGitHubAssetsSpec.groovy
src/test/groovy/edgeXReleaseGitTagSpec.groovy
src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
src/test/groovy/edgeXReleaseSnapSpec.groovy
src/test/groovy/edgeXReleaseSpec.groovy
src/test/groovy/edgeXSetupEnvironmentSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXGeneric.groovy
vars/edgeXInfraShipLogs.groovy
vars/edgeXReleaseDockerImage.groovy
vars/edgeXReleaseGitHubAssets.groovy
vars/edgeXReleaseGitTag.groovy
vars/edgeXReleaseGitTagUtil.groovy
vars/edgeXReleaseSnap.groovy
vars/edgex.groovy

Initial review to get ready for the master --> main conversion. Let me know if I missed anything.
Test Links :

feat: move to main as the default branch

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

fix: add use case for a null dockerfile (default value)

---

src/test/groovy/edgeXLTSSpec.groovy
vars/edgeXLTS.groovy

fix: use correct directory name when cloning

---

vars/edgeXLTS.groovy

fix: use proper dirName when checking isGoProject

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXRelease.groovy

bug: fix issues found during Jakarta release of sdk's

---

src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

ci: add edge case for device-sdk-c builder images

---

vars/edgeXSemver.groovy

fix: update github key

---

vars/edgeXSemver.groovy

fix: make script more robust due to concurrency issues

---

vars/edgeXSemver.groovy

fix: revert script to run outside the container

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

US2761
Test Links :
Original Behavior:
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/PR-138/1/consoleFull
New Behavior:
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/PR-138/3/consoleFull
Original Behavior:
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/device-coap-c/view/change-requests/job/PR-32/1/consoleFull
New Behavior:
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/device-coap-c/view/change-requests/job/PR-32/2/consoleFull
No
Refactor, should produce no functional changes.

refactor: remove unneeded agent call

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

Test Links :
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fsample-service/detail/PR-139/1/pipeline/141

feat: default Go version to 1.17

---

vars/edgex.groovy

Add the ireland branch. Not sure why it was not in here.
Test Links :

fix: add ireland release stream

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXInfraPublishSpec.groovy
src/test/groovy/edgeXInfraShipLogsSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXInfraPublish.groovy
vars/edgeXInfraShipLogs.groovy
vars/edgex.groovy

Test Links :
sample-service test:
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/view/change-requests/job/PR-141/7/console
device-coap-c
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/device-coap-c/view/change-requests/job/PR-36/2/console

feat: changes required to run on Ubuntu 20 agents

---

src/test/groovy/edgeXReleaseDocsSpec.groovy
vars/edgeXRelease.groovy
vars/edgeXReleaseDocs.groovy

New changes for edgex-docs release automation. This request came from the Lenny as part of this post-release activities for edgex docs.
Summary of change:
Automation should take place in edgexRelease.groovy as a new function.
Create "release" (kamakura, etc.) branch with these changes, commit and push
delete docs folder.
On the main branch, commit these changes:
Create a PR for each of these:
PR 1:
1. update index.html with current version number to make it the default, i.e. 2.2 (https://github.com/edgexfoundry/edgex-docs/blob/main/docs/index.html#L6)
2. update versions file with next release, i.e. 2.3 - Levski (https://github.com/edgexfoundry/edgex-docs/blob/main/docs/versions.json)
PR 2:
1. Update swagger links to use next version, i.e. 2.3, commit and push change. …

feat: new global function for docs releases

---

vars/edgex.groovy

feat: add new Golang 1.17 LTS base image

---

vars/edgex.groovy

feat: add kamakura as valid release branch

---

docs_src/index.md
mkdocs.yml
vars/edgeXDocker.groovy
vars/edgeXEmail.groovy
vars/edgeXGHPagesPublish.groovy
vars/edgeXInfraLFToolsSign.groovy
vars/edgeXInfraPublish.groovy
vars/edgeXNexusPublish.groovy
vars/edgeXReleaseDockerImage.groovy
vars/edgeXReleaseGitHubAssets.groovy
vars/edgeXSemver.groovy
vars/edgeXSnyk.groovy
vars/edgeXSwaggerPublish.groovy
vars/edgeXUpdateNamedTag.groovy
vars/edgex.groovy

Please point out any punctuation issues. I will attempt to fix in this PR.
Test Links :

docs: Additional documentation for existing functions

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

ci: add disableConcurrentBuilds to better handle git-semver issues

---

src/test/groovy/edgeXLTSSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXLTS.groovy
vars/edgex.groovy

feat: use Go version from go.mod file for LTS builds

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

feat: default Go version to 1.18

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

fix: fix issue with edgex-cli

---

vars/edgeXBuildGoApp.groovy

ci: add docker socket for pipelines that need docker-in-docker support

---

docs_src/tutorials/unit-testing-best-practices.md

Signed-off-by: cjoyv <chinu.joy@intel.com>
https://github.com/edgexfoundry/edgex-global-pipelines/issues/413
Test Links :

docs:Remove non-inclusive language abort from documentation

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: cjoyv <chinu.joy@intel.com>
Test Links :

docs: fix contributing guidelines link in ci-management

---

vars/edgex.groovy

ci: add levski as a valid release stream

---

src/test/groovy/README.md
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

This will change go-based builds to use 1.20
If approved, I'll merge on Monday. 
Test Links :

feat: default to use golang 1.20 in build images.

---

src/test/groovy/edgeXLTSSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXLTS.groovy
vars/edgex.groovy

fix: bug with isLTS relying on env.GIT_BRANCH inside cd-management repo

---

src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

fix: add lock around stage artifact to fix threading issues

---

vars/edgeXRelease.groovy

When doing dry-run it fails this echo statement:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-365/1/pipeline/280/
Test Links :

fix: dry-run use case

---

src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

ci: add support for golang 1.21

---

vars/edgex.groovy

ci: add napa release stream

---

vars/edgex.groovy

feat: add golang 1.21 lts image to candidate lts list

---

.github/workflows/release.yml

fix: check for optional "v"

---

src/test/groovy/edgeXSnykSpec.groovy
vars/edgeXSnyk.groovy

closed #448
#448 
Test Links :

feat: update Snyk scan docker image tag to latest

---

vars/edgeXSnyk.groovy

go 1.18 release notes: https://tip.golang.org/doc/go1.18#go-command
#450 
Test Links :

Fix Snyk error by adding git config safe.directory

---

vars/edgeXBuildGoParallel.groovy

fix: skip arm64 stage when running edgex-go PR validation

---

vars/edgeXBuildGoParallel.groovy

fix: Replace BRANCH_NAME with GIT_BRANCH in edgeXBuildGoParallel

---

vars/edgeXBuildGoParallel.groovy

fix: Update expression in edgeXBuildGoParallel

---

vars/edgeXBuildGoParallel.groovy

fix: Update when conditional in edgeXBuildGoParallel

---

src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgex.groovy

ci: add support for golang 1.23

---

vars/edgeXBuildGoApp.groovy

fix: skip arm64 stage when running GoAPP PR validation

---

vars/edgeXBuildCApp.groovy

Not run arm64 stage for device-sdk-c repository
Test Links :

fix: Not run arm64 stage for device-sdk-c repository

---

vars/edgeXBuildCApp.groovy

Update skip condition from Build LTS Release Image stage to Build Check
Test Links :

fix: Update skip condition from Build LTS Release Image stage to Build Check

---

vars/edgex.groovy

ci: add odessa release stream

---

vars/edgex.groovy

fix: add new goLTSImages 1.23

---

src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXReleaseOpenApiSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXRelease.groovy
vars/edgeXReleaseOpenApi.groovy

fix: remove openapi subfolder

---

docs_src/index.md
mkdocs.yml
src/test/groovy/edgeXBuildMultiArchSpec.groovy
vars/edgeXBuildMultiArch.groovy
vars/edgeXDocker.groovy

feat: add edgeXBuildMultiArch for nexus latest images

---

vars/edgeXBuildMultiArch.groovy
vars/edgeXDocker.groovy

fix: build all multi-arch images at once

---

vars/edgeXSemver.groovy

Test Links :
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/view/change-requests/job/PR-5156/5/consoleFull

fix: debug for git-semver
