vars/edgeXSemver.groovy

Use the latest per-arch image for Nexus3 staging.
Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

update git-semver image

---

vars/edgeXSetupEnvironment.groovy

This sets the default value for the pre-releases to dev.

Add default value for semver environment variable SEMVER_PRE_PREFIX

---

vars/edgeXInfraShipLogs.groovy

The edgeXInfraShipLogs global library needs to be updated in order to mount the system activity file from the host to the container running the lftools log publisher.  The lftools log publisher image now contains the sar utility and due to poor exception handling with the lftools logs deploy function it throws an exception and fails with "Cannot open /var/log/sa/sa13: No such file or directory" error.
@ernestojeda @jamesrgregg @lranjbar 

Add system activity file mount to LFtools

---

vars/edgeXInfraShipLogs.groovy

In order to access the system activity file the container needs to run in privileged mode.

add privileged option to lftools run

---

test/README.md
test/edgeXBuildDockerSpec.groovy
test/settings.xml
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy

- Fixing a bug where we aren't passing the maven settings environment variable into edgeXDockerLogin
- Also updating the unit tests for edgeXBuildDocker to include the new parameter releaseBranchOverride.
- Parameterized the port for the unit tests

Pass env variable into edgeXDockerLogin and update edgeXBuildDocker unit tests

---

vars/edgeXBuildGoApp.groovy

After reviewing the documentation https://jenkins.io/doc/book/pipeline/syntax/#agent, there is a subtle change needed for this to work.

add missing 'node' qualifier

---

vars/edgex.groovy

release stream changes

---

test/edgeXBuildGoAppSpec.groovy
test/edgexSpec.groovy
vars/edgex.groovy

- Updated isReleaseStream to match branch names exactly.
- Added unit tests for isReleaseStream
- Updated failing unit test for edgeXBuildGoApp

Update isReleaseStream to match exact names and add unit tests

---

test/edgeXBuildGoAppSpec.groovy
test/edgeXSnykSpec.groovy
vars/edgeXBuildGoApp.groovy

- Fixed issue with edgeXBuildGoApp referencing of ARM image
- Added unit tests for prepBaseBuildImage
- Fixed failing unit tests for edgeXSnyk

Update prepBaseBuildImage to handle arm golang image name correctly

---

Jenkinsfile

- Added a Test stage to execute **edgex-global-pipelines** unit tests leveraging the egp-unit-test ci build image. The test stage will only execute on Pull Requests and not merges.
**Observations**:
- The new Test stage adds approximately 3-4 minutes to the total build time. 
- I noticed that testing iterates over all dependencies and downloads something small (just a few KB). I'm not sure what its downloading, the dependencies have been pre-downloaded into the build image. We can potentially shave another minute if we pre-bake whatever its downloading for each dependency. I'll investigate but that work will not affect this PR, if anything it will require changes to the egp-unit-test ci build image. 
Resolves #58 

Add unit test stage to build automation

---

vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXGeneric.groovy

Also commented out the amd64 agent inside the parallel stage due to the fact the the originating node is already an amd64 agent and can be reused.

add beforeAgent to eval when before the agent spins up

---

vars/edgeXBuildGoApp.groovy

This is to fix potential permissions issues caused by un-stashing the coverage report from the testing stage. Issue seems intermittent as other builds have passed without any issue. However, I am reverting to this logic as we haven't had permissions issues in the past. I will look into a different approach to prevent this issue in the future.

enable extra agent call in parallel amd64 stage

---

vars/edgeXGeneric.groovy

This PR adds the ability to the `edgeXGeneric` pipeline to allow the user to provide an array of credentials to the underlying `pre_build`, `build` and `post_build` stages of the pipeline.
Test Links : N/A. Need to merge into master in order to test on the sandbox

add config.credentials to be provided to the pipeline

---

vars/edgeXBuildDocker.groovy

Currently there seems to be an issue with clair scanning images tagged with just the GIT_COMMIT hash. Since we always tag with `latest` in this pipeline, I am switch Clair to scan that tag.

fix issue with nexus GIT_COMMIT tagged images

---

vars/edgeXBuildDocker.groovy
vars/edgeXDocker.groovy

This PR enables easier scanning of pushed docker images by returning a list of images after they are pushed.

return list of tagged images for easier scanning

---

test/edgexSpec.groovy
vars/edgex.groovy

After this change: edgexfoundry/ci-management#584 the ARM64 label need to be updated to match.
Signed-off-by: Ernesto Ojeda ernesto.ojeda@intel.com
Test Links :

update label to ubuntu18.04-docker-arm64-4c-16g

---

test/edgeXClairSpec.groovy
test/edgeXSemverSpec.groovy
test/edgeXSnykSpec.groovy
vars/edgeXClair.groovy
vars/edgeXSemver.groovy
vars/edgeXSnyk.groovy

The respective ci-build-image references were updated to refer to the appropriate nexus location. The following table provides an overview of all ci-build-images and which ones required updating.
| CI Build Image | Status |
| --- | --- |
| edgex-docs-builder | No references found |
| edgex-gcc-base | Existing references did not require updating |
| edgex-golang-base | Existing references did not require updating |
| edgex-jmeter | No references found |
| edgex-jq | No references found |
| **edgex-klar** | **References were updated** |
| edgex-newman | No references found |
| **edgex-snyk-go** | **References were updated** |
| edgex-sonarqube | No references found |
| edgex-unit-test | Existing references did not require updating |
| robotframeworko | No references found |
| **git-semver** …

Update ci-build-image references to refer to the appropriate nexus location

---

test/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

Adding this parameter to be able to override the branch in didChange().
The default value of 'origin/master' causes issues because in cd-management we will not be committing to the master branch.

Add releaseBranch parameter to edgexRelease.collectReleaseYamlFiles

---

build.gradle
src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

Not Applicable.
I am of the opinion that we can remove the `gitTagDestination` field from the release YAML definition, it is redundant and the `repo` field can be used to determine both the git repo as well as the tag destination.
All code was unit tested:
```
> Task :test
Results: SUCCESS (10 tests, 10 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 24s
```

Implemented EdgeXReleaseGitTag function

---

src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXDocker.groovy
vars/edgeXReleaseDockerImage.groovy

I forgot to add the use-case for arm64 images. When I did I found a bug in the code with pulling the image name. This PR addresses the issue as well as make the code less verbose
Test Links :

fix issue with imageName vs image

---

Jenkinsfile
resources/releaseinfo.sh
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXGeneric.groovy
vars/edgex.groovy

Currently it is unclear what semver version of edgex-global-pipelines is being used when looking directly at the Jenkins log output. The current tagging only shows either `stable` or `experimental` a separate lookup is required to track down what version `stable` or `experimental` point to.
This PR adds a new shell script `resources/releaseinfo.sh` that can be used to list tag information out to the Jenkins build log. By default it will print both the `stable` and `experimental` tag information out to the log. A GitHub personal access token `GH_TOKEN_PSW` is required to call the script to avoid rate limiting issues.
**Note**: This will have to be merged and moved to `experimental` in order to test the functionality. This cannot be tested on the sandbox without first merging.
Default …

add edgex-global-pipelines release tag information to main pipelines

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

The following PR adds a new "Snap" stage for both x86 and ARM architectures. The stage is conditioned on whether a `snap/snapcraft.yaml` file exits. If it does, depending on if this is a PR or merge build it will either do a jobType 'build' or 'stage'. Due to these being declarative pipeline changes I did not add unit tests. However, I did functional tests on the LF sandbox to prove out similar code will work.
https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/device-modbus-go-snappy-snap/detail/device-modbus-go-snappy-snap/11/pipeline
This one is a bit tricky because the current device-grove-c job I was testing with is broken. However, I did achieve the same broken result as the [existing job](https://jenkins.edgexfoundry.org/view/Snap/job/device-grove-c-snap-master-stage …

implement Snap stages for x86 and ARM

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy

Because of so many existing repos having snap build failures I added an option to make the snap stage optional. By default it is turned off unless the developer specifies `buildSnap: true` in the call to `edgeXBuildGoApp` or `edgeXBuildCApp`. I also added an option to override the snap channel because I saw some use of that in the wild for named branch releases.
I also updated tests to use actual edgex.groovy impl to get proper results
- [] Bugfix

Add option for snapChannel and buildSnap

---

src/test/groovy/edgeXReleaseSnapSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXReleaseSnap.groovy
vars/edgex.groovy

**EdgeXReleaseSnap** will be integrated into cd-management and be responsible for releasing snaps for all the snap-enabled EdgeX repos.
**Pseudo-Code**:
```
get snap metadata from github repo /snap/snapcraft.yaml (snapName & architectures)
get snap info from snapcraft.io store for the snapName (channelmap & revisions)
iterate over architectures defined for the given Snap
if architecture is supported (amd64, arm64)
iterate over snapChannels to be released
set ARCH environment variable
if no snapRevision is provided
trackName is 'latest/edge' unless specified otherwise
get snapRevision from snap info retreived from the snapcraft.io store that matches architecture and trackName
call edgeXSnap
jobType: 'release',
snapChannel: snapChannel
snapRevision: snapRevision
snapName: snapName
``` …

Implement EdgeXReleaseSnap function

---

src/test/groovy/edgeXReleaseSnapSpec.groovy
vars/edgeXReleaseSnap.groovy

We discovered a bug during functional testing, due to how the snapcraft meta data file was being downloaded we noticed that data was being clobbered between parallel runs. To mitigate we will make the downloaded filename for snapcraft explicit by including the release name. 
https://github.com/edgexfoundry/cd-management/issues/3
NA 
Updated all impacted unit tests and verified all unit tests are working after the change was made.

Update to use explicit snapcraft filename

---

src/test/groovy/edgeXReleaseSnapSpec.groovy
vars/edgeXReleaseSnap.groovy

To facilitate release snaps we are leveraging the amd64-based edgex-snap-builder Docker image
https://github.com/edgexfoundry/cd-management/issues/3
NA
```
> Task :test
Results: SUCCESS (13 tests, 13 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 1m 19s
> Task :test
Results: SUCCESS (142 tests, 139 successes, 0 failures, 3 skipped)
BUILD SUCCESSFUL in 2m 40s
```

Update to use x86 snapcraft image for all snap releases

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

This adds an edgeXSemver bump command to the git tag release command sequence in order to bump the semver branch on the target repo to the next version level. 
- [] Feature
https://github.com/edgexfoundry/edgex-global-pipelines/issues/168
NA
Unit tests have been updated and new ones have been added to test the new logic:
```
> Task :test
Results: SUCCESS (16 tests, 16 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 22s
> Task :test
Results: SUCCESS (143 tests, 140 successes, 0 failures, 3 skipped)
BUILD SUCCESSFUL in 2m 39s
```

Add edgeXSemver bump command to command sequence

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

The default prefix for the pre axis in git-semver is 'pre'. Thus updating the semverBumpLevel default value to use 'dev' as the pre axis prefix.
NA
NA
Added a new test to assert the default value of semverBumpLevel and confirmed all other tests were successful:
```
> Task :test
Results: SUCCESS (17 tests, 17 successes, 0 failures, 0 skipped)
BUILD SUCCESSFUL in 21s
> Task :test
Results: SUCCESS (144 tests, 141 successes, 0 failures, 3 skipped)
BUILD SUCCESSFUL in 2m 35s
```

Set semverBumpLevel prefix default to be dev

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
vars/edgeXReleaseGitTag.groovy

This update will explicitly set the `SEMVER_BRANCH` environment variable to be the releaseStream, this is to ensure that the semver branch on the target repo is updated (i.e. bumped) correctly.
https://github.com/edgexfoundry/edgex-global-pipelines/issues/175
I did verify that withEnv spans docker image execution:
https://jenkins.edgexfoundry.org/sandbox/view/All/job/quick-test/configure
After this is merged and the experimental tag is updated, I will functionally test this change using the following PR:
https://github.com/edgexfoundry/cd-management/pull/8
Added new unit tests and verified all existing unit tests passed:
```
> Task …
```

Set SEMVER_BRANCH to be releaseStream

---

src/test/groovy/edgeXReleaseDockerImageSpec.groovy
vars/edgeXReleaseDockerImage.groovy

Low priority PR to allow the docker pull command to run during a dry run to verify source image actually exists.
Test Links :

add new env var to allow functional testing of docker pull command

---

src/test/groovy/edgeXSnykSpec.groovy
vars/edgeXSnyk.groovy

https://github.com/edgexfoundry/ci-build-images/issues/133
Test Links : N/A
Snyk base image has already been updated to 1.317.0 and the Go version is 1.13.  This addresses the issue discovered where the Snyk portal doesn't reflect the correct version of Go.
Signed-off-by: James Gregg <james.r.gregg@intel.com>

Update Snyk version to 1.317.0

---

Jenkinsfile

The global library is loaded implicitly from the global config so there is no need to load it again
Test Links :

remove loadGlobalLibrary

---

resources/edgex-publish-swagger.sh
resources/toSwaggerHub.sh
src/test/groovy/edgeXSwaggerPublishSpec.groovy
vars/edgeXSwaggerPublish.groovy

Global function for SwaggerHub publishing. A wrapper of existing shell scripts to deploy to swagger hub.
*Adds ability to optionally specify a different "owner" (Defaults to EdgeXFoundry1)
#188 
Test Links :
[Sand Box Link Fails due to lack of SwaggerHub Credentials on Sandbox](https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional%20Testing/job/edgeXSwaggerPublish/2/console)
Using my Personal SwaggerHub Token it lets me push this to my own account using a forked version of sample-service
No
No
edgex-go/Jenkinsfile is the only place swaggerhub publish functionality exists. To take advantage of this global function this is …

Global function for SwaggerHub publishing.

---

vars/edgeXSnap.groovy

Currently, there is no real easy way to test alternate versions of the snap builder image. The PR gives us that ability.
Test Links :

add ability to override snap builder image version tag

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

Certain repos e.g. [device-sdk-c](https://github.com/edgexfoundry/device-sdk-c/tree/geneva) are creating `geneva` branches and git-semver and other stages are not running due to geneva not being considered a valid release stream. This PR fixes that issue.
Test Links :

feat: add geneva as a valid release stream

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXSwaggerPublishSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXSwaggerPublish.groovy

Signed-off-by: Cherry Wang <cherry@iotechsys.com>
Fix #221 
Test Links :
Related PR [edgex-go #2644](https://github.com/edgexfoundry/edgex-go/pull/2644)

Change swagger path since the path has updated from api/openapi to openapi  on edgex-go

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildDockerSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXClairSpec.groovy
src/test/groovy/edgeXDockerLoginSpec.groovy
src/test/groovy/edgeXGenericSpec.groovy
src/test/groovy/edgeXInfraLFToolsSignSpec.groovy
src/test/groovy/edgeXNexusPublishSpec.groovy
src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
src/test/groovy/edgeXReleaseDockerImageSpec.groovy
src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
src/test/groovy/edgeXReleaseSnapSpec.groovy
src/test/groovy/edgeXSwaggerPublishSpec.groovy
src/test/groovy/edgeXUpdateNamedTagSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXSetupEnvironment.groovy

- Continuing with the theme of removing unnecessary mocks; wrapping tests with try/catch when testing error was unnecessary. I removed the unneeded code and all tests passed.
- Also updated error mocks to check for explicit message.
- Reverted `edgeXSetupEnvironment` to use idiom for setting environment variables that doesn't incur a `RejectedAccessException` in EdgeX Jenkins
- Added missing mocks for `sh` in `edgeXSwaggerPublishSpec`
NA
```
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
> Task :test
Results: SUCCESS (188 tests, 186 successes, 0 failures, 2 skipped)
BUILD …
```

Remove unnecessary exception wrapping when testing error

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

- Enabled Snap stage for edgeXBuildGoParallel
- Disable Snap stage on merge to master
- Use specific build agents for Snap stages to speed up builds
- Remove SNAP_CHANNEL to disable publishing to the Snap store
Fixes: #229 
Test Links :
- https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/Functional-Testing%2Fedgex-go-pipeline-test/detail/edgex-go-pipeline-test/4/
- https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/Functional-Testing%2Fedgex-go-pipeline-test/detail/edgex-go-pipeline-test/6/pipeline
No
No

feat: Snap modifications

---

vars/edgeXBuildGoParallel.groovy

Per the WG meeting today 08/27/2020 we are disabling the Snap stage for `edgeXBuildGoParallel`.
Test Links :

revert: Disable Snap arm64 stage

---

src/test/groovy/edgexSpec.groovy
vars/edgex.groovy

To support developers in Go 1.15, we have added a new image to ci-build-images: https://github.com/edgexfoundry/ci-build-images/tree/golang-1.15. This PR adds the option to use this base image.
Test Links :

feat: add new option for Go 1.15 base image

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Make the default Go version 1.15 unless overridden by user.
Test Links :

feat: update default version of Go to 1.15

---

resources/edgex-publish-swagger.sh

(fix) allow yml as well as yaml extension to be used with edgex-publish-swagger
#237 
Test Links :
Closes #237

(fix) allow yml as well as yaml extension to be used with edgex-publish-swagger

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Move the `go version` to the prep stage to always print the go version into the Jenkins log.
Test Links :

refactor: move go version to prep stage

---

Jenkinsfile
vars/edgeXBuildGoApp.groovy

Add an additional condition for when `edgeXUpdateNamedTag` is executed within our Pipelines.  Because `edgeXUpdateNamedTag` updates the experimental/stable tag on the version tag **it should only** execute when **edgeXSemver** creates the version tag.
To enable jobs to be executed repeatedly without the affect of tagging/bumping a new version tag every time; **edgeXSemver** sets the environment variable `env.GITSEMVER_HEAD_TAG` when it detects that HEAD is tagged, doing so, directs edgeXSemver to ignore all subsequent tag, bump and push commands (unforced). Thus if this environment variable is set then we should not call `edgeXUpdateNamedTag` because the new version tag will not exist.
Please check if your PR fulfills the following …

Add condition for calling edgeXUpdateNamedTag

---

src/test/groovy/edgeXInfraPublishSpec.groovy
vars/edgeXInfraPublish.groovy

Using the lfInfraShipLogs function will enable the collection of job
cost data, and keep the function up to date with global-jjb.
Issue: LF-Jira RELENG-3175
Signed-off-by: Eric Ball <eball@linuxfoundation.org>
Tested here: https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgexfoundry/job/sample-service/job/master/2/
Job 3 was also a test of this change, without the @Library line (I wasn't sure if it was necessary with the library added at the org level, but it turns out it is).
This adds an import of the lf-pipelines library, which needs to be added to the org to function. I added it on the sandbox, and will add it in prod once this is approved. The library can be found here: …

Switch to lfInfraShipLogs, from LF Pipelines lib

---

src/test/groovy/edgeXCodecovSpec.groovy
vars/edgeXCodecov.groovy

CodeCov has been broken for about 3 months. I think this had to do with a security change in Jenkins. This PR fixes the CodeCov upload.
Test Links : https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fsample-service/detail/PR-58/11/pipeline

fix: issue with CodeCov uploader

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
src/test/groovy/edgeXSemverSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXReleaseGitTag.groovy
vars/edgeXSemver.groovy

**TESTING IN PROGRESS**
- Made `edgeXSemver` more robust by enabling it to handle use cases that were previously resulting in tag errors.
-- updated how to detect if HEAD is tagged and conditions for when to set GITSEMVER_HEAD_TAG which is used to facilitate re-execution of build jobs without having semver continue tagging
-- leverage GITSEMVER_INIT_VERSION to hold initial semver version
-- added logic to remove remote/local GITSEMVER_INIT_VERSION tag when force tag; specific edge case condition
-- converted prints to echo statements to facilitate assertions in unit tests
- Updated `edgeXBuildGoApp` and `edgeXReleaseGitTag` global functions to consume `edgeXSemver` in a standard way
- Added `edgeXSemverSpec` unit tests to test multiple `edgeXSemver` use cases
Please check if your PR …

Update edgeXSemver to resolve semver tag issue

---

Jenkinsfile

fix: Moving to explicit check of git branch name from edgex.isReleaseStream()
Test Links :

Moving to explicit check of git branch name from edgex.isReleaseStream()

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildDockerSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXSnykSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXSnyk.groovy

This PR modifies `edgeXSnyk.groovy` to allow on-demand testing of images that are pushed to a docker registry.
edgeXSnyk should:
- implement on-demand testing of docker images (pushed to nexus)
- notify distribution list of users when vulnerabilities are found
- allow ignoring of Snyk findings via the `.snyk` policy
Test Links :
See jobs under this PR:
`edgeXBuildGoApp`
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/view/change-requests/job/PR-77/
`edgeXBuildGoAppParallel`
https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional-Testing/job/eojeda-edgex-go-snyk/4/console
Example HTML Email:
Example …

feat: inline Snyk docker image scan

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Currently any `docker pull` commands issued by the pipelines are anonymous due to no docker login commands being issues until the docker push stage. Due to new rate limits being imposed by docker for `docker pull` commands, we now should be doing authenticated requests. This PR adds the `docker login` to the beginning of each prep stage when nodes are spun up to make sure requests are authenticated.
Test Links :
https://jenkins.edgexfoundry.org/sandbox/blue/organizations/jenkins/Functional-Testing%2Feojeda-edgex-go-experimental/detail/eojeda-edgex-go-experimental/6/pipeline …

refactor: docker login in all prep stages

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

This is a temporary function I added to all the pipelines to enable the Nexus registry mirror on the fly while the LF updates the packer images.
Testing with this build: https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fsample-service/detail/PR-83/1/
Test Links :

fix: add function to enable docker registry mirror

---

src/test/groovy/edgeXBuildGoModSpec.groovy
vars/edgeXBuildGoMod.groovy

Per the DevOps WG meeting on 12/3/20, we are changing the way go modules are versioned to match the other Go projects. (So bumping pre-release version of the `semver 1.x.x-dev.x`)
Test Links :

feat: go modules no longer bump patch semver

---

resources/snap-build.sh
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXSnap.groovy

Migrate `edgeXSnap` to use new snap-build.sh script provided by Canonical.
Original source script is here: https://github.com/siggiskulason/ci-management/blob/snap-build-snap-script/shell/build-snap.sh.
Migrated to work within edgex-global-pipelines: [resources/snap-build.sh](./resources/snap-build.sh)
Test builds can be found here:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-go/detail/PR-2898/9/pipeline/256
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fapp-service-configurable/detail/PR-124/33
Test Links :

feat(snap): Use new native build script

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildDockerSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

We are running into Snyk limits so I am disabling the docker scans until we closer to the Ireland release. Then they can be enabled globally or on specific repositories.
Test Links :

feat: allow Snyk docker scans to be disabled via config

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXRelease.groovy
vars/edgeXReleaseGitTag.groovy
vars/edgeXReleaseGitTagUtil.groovy

Update edgeXrelease* functions to facilitate releasing edgeX repos from a specific commit Id.
Fixes 
https://github.com/edgexfoundry/cd-management/issues/110
Test edgeXReleaseGitTag
https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional-Testing/job/test-edgeXReleaseGitTag/6/
Test edgeXRelease
https://jenkins.edgexfoundry.org/sandbox/view/All/job/Functional-Testing/job/test-edgeXRelease/4/
Unable to test edgeXRelease end-to-end since build command is passed in a relative path for the build to execute which doesn't exist in Sandbox, and would be difficult to emulate. Thus will rely on testing edgeXRelease and build using PR …

Implement ability to release an EdgeX code repo from a specific commit

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXGeneric.groovy

Previously, the LF's job cost scripts could not take into account the
agents that are dynamically allocated when an "agent" block is used
within a parallel stage. A new function has been added to the LF's
pipeline library that is intended to be run in a post block after any
parallel stage that uses a new agent.
This change also includes some minor whitespace cleanup in affected
files, as well as adding a license to edgeXGeneric and updating
copyright dates.
Issue: LF-Jira RELENG-3207
Signed-off-by: Eric Ball <eball@linuxfoundation.org>
Test Links :

Parallel jobs: get cost data from dynamic nodes

---

resources/build-log-extract.sh
resources/email/build-notification-template.html
src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildDockerSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXEmailSpec.groovy
src/test/groovy/edgeXEmailUtilSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXEmail.groovy
vars/edgeXEmailUtil.groovy
vars/edgeXInfraPublish.groovy

New feature to send emails for build failures.
#312 
Test Links :

feat: Add ability to send HTML emails on build failure

---

vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Fix a reference to an old method I initially setup and refactored to the edgeXEmail class.
Test Links :

fix: reference to old email method

---

vars/edgeXEmailUtil.groovy

`jobDetails` parameter of generateEmailTemplate should be defaulted null to allow empty parameters.
Test Links :

fix: jobDetails should be defaulted to null

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
vars/edgeXBuildGoApp.groovy

Fixes permissions with the archives directory. The default value of `ARTIFACT_ROOT` is `archives/bin`, so the chown is applied to the parent directory hence the `chown ... ${ARTIFACT_ROOT}/..`. I did not want to hardcode the directory so that is why I did the `..`
Test Links : https://jenkins.edgexfoundry.org/sandbox/job/Functional-Testing/job/edgex-cli-test/4/console

fix: update permission for build artifacts

---

vars/edgeXRelease.groovy

This addresses [#115 - EdgeX DevOps: release automation fails to bump semver tag when re-releasing a repo with the same version](https://github.com/edgexfoundry/cd-management/issues/115)
**Prior Behavior:**
**cd-management releases sample-service 4.1.36**
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/view/change-requests/job/PR-151/1/console
**Sample service failed when staged.** 
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/master/144/
This causes sample-service to be tagged to 4.1.36 but fails to bump the version so semver is set to 4.1.36 afterwards
Subsequent sample-service builds fail due to it being tagged at 4.1.36 and semver being set to 4.1.36 still. It also will not bump semver to get out of this stuck state. …

fix: ensure bump always happens if tag happens.

---

src/test/groovy/edgeXInfraPublishSpec.groovy
src/test/groovy/edgeXInfraShipLogsSpec.groovy
src/test/groovy/edgexSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildDocker.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXInfraPublish.groovy
vars/edgeXInfraShipLogs.groovy
vars/edgex.groovy

I created this PR to mainly tackle an inefficiency around two parts the pipelines:
1. Temporary code to setup a docker proxy. This was only needed for a short time
2. The `lfParallelCostCapture` introduced quite a long delay in the pipeline due to unnecessary python steps
I also updated global-jjb to a new version to make sure the scripts line up https://github.com/lfit/releng-pipelines 
Working build ARM stage went from ~3.5 minutes down to 3 secs, x86_64 went from ~40 secs down to 3 seconds
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/view/change-requests/job/PR-122/3/consoleFull
**x86_64**
```
18:49:49  ---> job-cost.sh
18:49:49  lf-activate-venv(): INFO: …
```

Pipeline optimizations

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Make the `Dockerfile.build` file optional in the pipeline. If it exists in the workspace, the code will function as is, if it is not found we will use `--target` option that Docker provides to only build the `builder` stage in the Dockerfile.
#345 
Test Links :
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fsample-service/detail/PR-125/1/pipeline/169

feat: make Dockerfile.build optional

---

vars/edgeXBuildCApp.groovy

Should fix issues with image names like:
Before:
```
device-coap-c --> deviceoap
device-cranberry-c --> deviceranberry
```
After:
```
device-coap-c --> device-coap
device-cranberry-c --> device-cranberry
```
etc
Test Links :

fix: use regex for default docker image name

---

src/test/groovy/edgeXBuildCAppSpec.groovy
src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildCApp.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

Add missing use-case for repo's that don't build docker images like, sdk's and go-mods
Test Links :
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/PR-129/3/

feat: allow retagging of base image when no Dockerfile's exist

---

vars/edgeXInfraPublish.groovy

This bug was introduced when I made the change to dockerize the job cost code a few weeks ago.
Here is a test job where it was failing before and is fixed after:
Before:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fci-build-images/detail/PR-173/3/pipeline
After:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fci-build-images/detail/PR-174/1/pipeline/
Test Links :

fix: fix archives directory permissions

---

vars/edgeXInfraPublish.groovy

Sometimes builds do not have an `archives` directory. This fix checks to make sure it does.
Sample service build
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/view/change-requests/job/PR-130/1/consoleFull
Test Links :

fix: add check to make sure archives directory exists

---

src/test/groovy/edgeXBuildGoParallelSpec.groovy
vars/edgeXBuildGoParallel.groovy

This fix really only applies to edgeXBuildGoParallel and instead of just pulling and retagging will create a new image specifically with `go mod download` being called. This will pre-download all the dependencies and allow to keep performance gains. Doing it inline for now to keep the footprint small.
Tested with edgex-go: https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-go/detail/PR-3651/4/pipeline/128
Test Links :

fix: build inline image with go modules downloaded

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

After today's DevOps WG meeting, it was decided that the go.sum would start being commited back into the repo. Due to this, `go mod tidy` is no longer required to be called. So this change will only run `go mod tidy` if `go.sum` does not exist and we are at `Go 1.16`
Test Links :

ci: check if go.sum does not exist before running go mod tidy

---

src/test/groovy/edgeXReleaseGitTagSpec.groovy
src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
src/test/groovy/edgeXSemverSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXReleaseGitTag.groovy
vars/edgeXReleaseGitTagUtil.groovy
vars/edgeXSemver.groovy

Update to leverage Python-based `git-semver` capability: [User Story 3314](https://dev.azure.com/brokenbluesky/IOTG%20RBHE/_workitems/edit/3314)
Build Pipeline using edgeXBuildGoApp
[Build Pipeline #37](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/main/37/)
[Build Pipeline #38](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/main/38/)
Build Pipeline using explicit edgeXSemver:
[Build Pipeline #39](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/sample-service/job/main/39/)
Build Pipeline using edgeXBuildGoApp
[Build Pipeline …

feat: use Python-base git-semver capability

---

src/test/groovy/edgeXBuildGoAppSpec.groovy
src/test/groovy/edgeXBuildGoParallelSpec.groovy
src/test/groovy/edgeXSnykSpec.groovy
vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXSnyk.groovy

This new features allows for:
- Custom snyk project name to be used to help create unique branch level projects in Snyk (this is needed to distinguish the main from jakarta cli projects)
- Snyk Debug config param to allow more insight into Snyk cli failures
Functional Test Job:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fsample-service/detail/main/65/pipeline/615
The project also shows up correctly on the Snyk side.
Test Links :

feat: Snyk enhancements for projectName and debug

---

src/test/groovy/edgeXSemverSpec.groovy
vars/edgeXSemver.groovy

Pin py-git-semver Docker image version to mitigate weirdness with jakarta-based builds pulling down older version of image.
Test Links :

fix: pin py-git-semver docker image version

---

src/test/groovy/edgeXReleaseDocsSpec.groovy
vars/edgeXReleaseDocs.groovy

This change bumps the version in mkdocs.yml, to be set for the next release (usually a manual activity done after the release). This will create a diff that looks like this:
```diff
diff --git i/mkdocs.yml w/mkdocs.yml
index 564219be..6690a360 100644
--- i/mkdocs.yml
+++ w/mkdocs.yml
@@ -1,6 +1,6 @@
site_name: EdgeX Foundry Documentation
docs_dir: ./docs_src
-site_dir: ./docs/2.2
+site_dir: ./docs/2.3
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Michael Johanson'
site_url: 'https://edgexfoundry.github.io/edgex-docs/'
```
Test Links :

feat: add new functionality to bump version after release

---

vars/edgeXBuildGoApp.groovy
vars/edgeXBuildGoParallel.groovy

This PR is a fix for the issues we are seeing with golangci-lint and `go build` where the builds are failing with this new error (introduced in Go 1.18).
```
13:16:26  level=warning msg="[linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
13:16:26  cmd/core-command/main.go:1: : error obtaining VCS status: exit status 128
13:16:26  	Use -buildvcs=false to disable VCS stamping. (typecheck)
```
Due to different file permissions in the Jenkins `$WORKSPACE`, when Go runs:
```
13:40:29  git status --porcelain
```
It returns:
```
13:40:29  fatal: unsafe repository ('/w/workspace/dry_app-functions-sdk-go_PR-1150' is owned by someone else)
```
Which causes the Go …

ci: add privileged to fix issues with Go 1.18 and AppArmor

---

src/test/groovy/edgeXDockerSpec.groovy
vars/edgeXBuildGoParallel.groovy
vars/edgeXDocker.groovy

Update `docker-compose` references to use new docker compose v2. Parallel is supported by default in docker-compose v2 so I removed the check for parallel.
Test Links :

feat: update to use new docker compose v2 syntax

---

resources/update-named-tag.sh
src/test/groovy/edgeXReleaseSpec.groovy
vars/edgeXRelease.groovy

https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/PR-359/20/console
https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/PR-359/21/console
In both functional tests the v5.1 tag was created and pointed to the released version.
Test Links :

feat: create vanity tag on release

---

vars/edgeXRelease.groovy

fix: sleep constant duration instead of RANDOM duration

---

vars/edgeXBuildGoApp.groovy

Not run arm64 stage for go-mod and go-sdk repositories
Test Links :

fix: Not run arm64 stage for go-mod and go-sdk repositories
